version: "3.8"
services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8001:8000"
    environment:
      # - APP_ENV=local
      - APP_ENV=${APP_ENV}
      - DYNAMODB_TABLE=agri-poc
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
    depends_on:
      - dynamodb-local
      - dynamodb-init
    env_file:
      - .env

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8002:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  dynamodb-init:
    image: amazon/aws-cli
    container_name: dynamodb-init
    depends_on:
      - dynamodb-local
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./scripts/init-dynamodb.sh:/init-dynamodb.sh
    entrypoint: [ "sh", "/init-dynamodb.sh" ]